### ISSUE TITLE
Resubmissions

### ISSUE THREAD

**Issue by jwright** [UM-USElab/gradecraft-development#1532]
As a student
When I update a submission after it has been submitted
Then it should be considered a resubmission
So that it can be communicated with the professor that it is a resubmission

**Comment by jwright** [comment]
A resubmission is when:
* An assignment can accept resubmissions
* A student updates a submission, and 
  * The professor has given a grade
  * It is before the resubmission until date

**Comment by jwright** [comment]
* Student can modify a submission up until the due date - not a "resubmission"

**Comment by jwright** [comment]
Resubmissions currently are just grades that are created after the submission updated at

**Comment by jwright** [comment]
Related to #875

**Comment by jwright** [comment]
- [ ] Display that the submission will be a resubmission when the student is updating it

**Comment by chcholman** [comment]
@jwright I believe it's the reverse - Resubmissions are submissions that have been updated after the grade updated at date

**Comment by jwright** [comment]
@chcholman Here is what I believe the changes will be based on a preliminary look at submissions and grades. I just wanted to see what you thought about this architecture if anything. Please let me know if you see any issues.

1. Create a model/table called `graded_submissions` which will be defined as the following:

```
submission_id => integer (FK to submissions)
grade_id => integer (FK to grades)
transaction_id => integer (FK to versions)
graded_at => date/time when the grade was assigned
created_at
updated_at
```

2. Create an entry above when an assignment is graded for a student. This will assign a specific grade to a specific version of the submission.

3. Resubmissions will be defined as anything that already has a `GradedSubmission`

4. Resubmissions will be allowed based on criteria above (assignment allows it and it is before the resubmission allowed until date)

5. Create an entry above when a resubmission is graded

6. Change the scope for `Submission.resubmitted` to use the `GradedSubmission` relation

7. Remove the `Submission#resubmitted` boolean column from the db

8. Remove the `Submission#graded` boolean column from the db

9. Remove the `Submission#submitted_at_date` column from the db

10. Remove the `Submission#released_at` column from the db

11. Remove the `Submission#attachment_*` columns from the db

12. Remove the `Submission#text_feedback` column from the db

**Comment by chcholman** [comment]
@jwright I think this makes sense. Two questions: 

1) Resubmissions are an edit on the original submission that identifies what version has yet to be graded, yes? They aren't a totally new submission? (I'm fairly sure of this, but wanted to confirm.)

2) In the second step 1, you note "assign a specific grade to a specific version of the submission" - we currently prevent students from earning multiple grades for a single assignment here: https://github.com/UM-USElab/gradecraft-development/blob/master/db/schema.rb#L528 

It seems like, in order to associate a specific grade with a specific submission, we're going to need to undo this requirement, or else add versioning to grades as well (a feature I want, and am very happy to implement now if it makes sense - but it seems like we might need to do that first?). 

If we're removing the index, we need to revise the method to recalculate students' total scores, as it is currently just a sum of all their grades in the course and would need to become smart enough to only include their latest grade for an assignment.

**Comment by jwright** [comment]
@chcholman

1. Yes, this is correct. Basically resubmissions are additional "transactions" within a submission in the versions table. I will explain more below.

2. I am not sure this is needed at this point. I am thinking that the grade will hold the "final grade" and maybe we add `score` to the `graded_submissions`. I will give an example below. It may not be correct but I want to show you what I am thinking with data.

Here is an example:

1. A professor gives a student a grade on a submission. Here is an example of what the data would look like.

```
assignments:
  id: 123
```

```
grades:
  id: 456
  assignment_id: 123
  submission_id: 789
  student_id: 1
  raw_score: 10,000
  status: "Graded"
```

```
submissions:
  id: 789
  student_id: 1
```

```
versions:
  transaction_id: 333
```

```
graded_submissions:
  id: 1
  transaction_id: 333
  submission_id: 789
  grade_id: 456
  score: 10,000
  graded_at: current_datetime
```

2. A student updates a submission

```
submissions:
  id: 789
  student_id: 1
  link: <new value>
```

```
versions:
  transaction_id: 444
```

3. Professor grades resubmission

```
submissions:
  id: 789
  student_id: 1
  link: <new value>
```

```
versions:
  transaction_id: 444
```

```
grades:
  id: 456
  assignment_id: 123
  submission_id: 789
  student_id: 1
  raw_score: 15,000
  status: "Graded"
```

```
graded_submissions:
  id: 2
  transaction_id: 444
  submission_id: 789
  grade_id: 456
  score: 15,000
  graded_at: current_datetime
```

Does this make sense? Is this the way we want to approach it or is having multiple grades at this point worth it? Does having multiple grades per assignment buy us anything in the future besides grading resubmissions?
